/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { GovernorElectionContract } from "./GovernorElection";
import { MigrationsContract } from "./Migrations";
import { ProposalElectionContract } from "./ProposalElection";
import { RomeElectionContract } from "./RomeElection";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "GovernorElection"): GovernorElectionContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "ProposalElection"): ProposalElectionContract;
      require(name: "RomeElection"): RomeElectionContract;
    }
  }
}

export {
  GovernorElectionContract,
  GovernorElectionInstance,
} from "./GovernorElection";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  ProposalElectionContract,
  ProposalElectionInstance,
} from "./ProposalElection";
export { RomeElectionContract, RomeElectionInstance } from "./RomeElection";
