/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { GovernorElectionContract } from "./GovernorElection";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";
import { ProposalElectionContract } from "./ProposalElection";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "GovernorElection"): GovernorElectionContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
      require(name: "ProposalElection"): ProposalElectionContract;
    }
  }
}

export {
  GovernorElectionContract,
  GovernorElectionInstance,
} from "./GovernorElection";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  ProposalElectionContract,
  ProposalElectionInstance,
} from "./ProposalElection";
